"""add_google_oauth_fields

Revision ID: 4838883a80a9
Revises: afc18ce3df71
Create Date: 2026-01-26 23:52:46.704498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4838883a80a9'
down_revision: Union[str, Sequence[str], None] = 'afc18ce3df71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # Add as nullable first
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    # Update existing rows
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # Now make it not null
    op.alter_column('users', 'auth_provider', nullable=False)
    
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
