"""add_trend_column

Revision ID: 6c8c7c9dc09b
Revises: 5562bd2f04f1
Create Date: 2026-01-22 12:47:06.361419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8c7c9dc09b'
down_revision: Union[str, Sequence[str], None] = '5562bd2f04f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('trend', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'trend')
    # ### end Alembic commands ###
