"""Add User Onboarding Fields

Revision ID: 87ca75276ce2
Revises: e985bdea3de9
Create Date: 2026-02-03 09:54:31.499846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ca75276ce2'
down_revision: Union[str, Sequence[str], None] = 'e985bdea3de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('professional_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('primary_stressor', sa.String(), nullable=True))
    op.add_column('users', sa.Column('coping_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coping_style')
    op.drop_column('users', 'primary_stressor')
    op.drop_column('users', 'years_experience')
    op.drop_column('users', 'professional_role')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
